services:
  auction-service:
    build: .
    container_name: auction-service
    ports:
      - "50054:50051"
    env_file:
      - .env
    depends_on:
      - auction-db
    networks:
      - auction-service-network

  auction-db:
    image: postgres:15-alpine
    container_name: auction-service-db
    env_file:
      - .env
    environment:
      - PGPORT=5434
    ports:
      - "5434:5434"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auction-service-network

networks:
  auction-service-network:
    driver: bridge

volumes:
  postgres-data:
